# My alacritty config file
# author = inatagan
# https://github.com/inatagan

# Theme: Cyber Punk Neon
[general]
import = [
    "~/.config/alacritty/themes/themes/cyber_punk_neon.toml"
]

# Window settings
[window]
dimensions = { columns = 118, lines = 34 }
padding = { x = 10, y = 10 }
dynamic_padding = true
decorations = "None"
opacity = 0.9

# Scrolling settings
[scrolling]
history = 10000
multiplier = 3

# Font settings
[font]
normal = { family = "0xProto", style = "Regular" }
bold = { family = "0xProto", style = "Bold" }
italic = { family = "0xProto", style = "Italic" }
bold_italic = { family = "0xProto", style = "Bold Italic"}
size = 14.0

# Bell settings
[bell]
animation = "EaseOutCubic"
duration = 100
color = "#523874"

# Cursor settings
[cursor]
style = { shape = "Block", blinking = "On" }
blink_interval = 750
blink_timeout = 5
unfocused_hollow = true

# Mouse settings
[mouse]
hide_when_typing = true

# Keybindings
[keyboard]
bindings = [
{ key = "Return", mods = "Control|Shift", action = "SpawnNewInstance" },
{ key = "W", mods = "Control|Shift", action = "Quit" },
]
